#!/usr/bin/env bash

set -e

CMD=$1

#export APPBRANCH=${APPBRANCH:-$(git rev-parse --abbrev-ref HEAD)}
export APPBRANCH=any


# Create a .env file so that we may use subsequent docker-compose
# commands directly
cat > .env << End-of-env
APP_USER_ID=${APP_USER_ID:-$(id -u)}
APP_GROUP_ID=${APP_GROUP_ID:-$(id -g)}
APP_WEB_PORT=${APP_WEB_PORT:-8032}
APP_PGSQL_PORT=${APP_PGSQL_PORT:-8553}
End-of-env

DOCK_COMPOSE_OPTIONS="--env-file .env -p jelix-resque-${APPBRANCH}-tests"


if [ "$CMD" == "reset" ]; then
    # Stop/Remove containers
    docker-compose $DOCK_COMPOSE_OPTIONS rm -sfv || true
    docker image rm jelix-resque-${APPBRANCH}-tests_ || true

    # Clean postgres volume
    docker volume rm "jelix-resque_${APPBRANCH}_pg_data" || true
    exit 0
elif [ -z "$CMD" ]; then
    CMD="up"
else
  shift
fi

docker-compose $DOCK_COMPOSE_OPTIONS $CMD "$@"
